services:
  - type: web
    name: prod-graphql-skilled
    plan: starter
    env: docker
    region: oregon
    autoDeploy: false
    healthCheckPath: /healthz
    envVars:
      - key: HASURA_GRAPHQL_DATABASE_URL
        fromDatabase:
          name: prod-db-skilled
          property: connectionString
      - key: HASURA_GRAPHQL_ENABLE_CONSOLE
        value: true
      - key: HASURA_GRAPHQL_UNAUTHORIZED_ROLE
        value: anonymous
databases:
  - name: prod-db-skilled
    postgresMajorVersion: 16
    region: oregon
